"""
Post Comment Node — rule-based, no LLM.
Posts the review as a comment to the GitHub PR.
Skips gracefully if GITHUB_TOKEN is not set (display-only mode).
"""
import logging
from agent.state import ReviewState
from models.schemas import CriticReport, Finding
from utils.github import post_pr_comment

logger = logging.getLogger(__name__)

SEVERITY_EMOJI = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}
VERDICT_EMOJI  = {"APPROVE": "✅", "REQUEST_CHANGES": "❌", "NEEDS_DISCUSSION": "💬"}


def _format_comment(report: CriticReport) -> str:
    verdict_emoji = VERDICT_EMOJI.get(report.verdict, "💬")
    lines = [
        f"## {verdict_emoji} AI Code Review — {report.verdict}",
        "",
        f"_{report.summary}_",
        "",
        f"**Verdict reason:** {report.verdict_reason}",
        "",
    ]

    if report.findings:
        lines += [
            "### Findings",
            "",
            "| Severity | Category | File | Line | Issue | Suggestion |",
            "|---|---|---|---|---|---|",
        ]
        for f in report.findings:
            emoji = SEVERITY_EMOJI.get(f.severity, "")
            lines.append(
                f"| {emoji} {f.severity} | {f.category} | `{f.file_name}` "
                f"| {f.line_number} | {f.message} | {f.suggestion} |"
            )
    else:
        lines.append("_No issues found._")

    lines += ["", "---", "_Generated by pr-review-agent-lg_"]
    return "\n".join(lines)


def post_comment_node(state: ReviewState) -> dict:
    report = state.get("critic_report")
    pr_url = state.get("pr_url", "")

    if not report:
        logger.warning("[POST_COMMENT] no critic_report in state — skipping")
        return {}

    comment_body = _format_comment(report)

    if not pr_url:
        logger.info("[POST_COMMENT] no pr_url — display-only mode")
        return {}

    try:
        posted = post_pr_comment(pr_url, comment_body)
        if posted:
            logger.info("[POST_COMMENT] comment posted to %s", pr_url)
        else:
            logger.info("[POST_COMMENT] GITHUB_TOKEN not set — display-only mode, comment not posted")
    except Exception as e:
        logger.warning("[POST_COMMENT] failed to post comment (non-fatal): %s", e)

    return {}
